# Generated by Django 5.2.3 on 2025-06-10 23:19

import django.db.models.deletion
import mapbox_location_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=5)),
                ('establishment_hours', models.CharField(max_length=12)),
                ('website', models.URLField()),
                ('location', mapbox_location_field.models.LocationField(default=[0.0, 0.0], map_attrs={})),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_start_time', models.TimeField()),
                ('deal_end_time', models.TimeField()),
                ('deal_day_of_week', models.CharField(max_length=10)),
                ('deal_type', models.CharField(max_length=20)),
                ('deal_details', models.CharField(max_length=300)),
                ('establishment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Deals', to='restaurants.establishment')),
            ],
        ),
    ]
