# Generated by Django 4.2.20 on 2025-04-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("zipcode", models.CharField(max_length=5)),
                ("establishmentHours", models.CharField(max_length=12)),
                ("website", models.URLField()),
                ("happyHourStartTime", models.TimeField()),
                ("happyHourEndTime", models.TimeField()),
                ("happyHourDayofWeek", models.CharField(max_length=5)),
            ],
        ),
    ]
