# Generated by Django 4.2.20 on 2025-04-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dealStartTime", models.TimeField()),
                ("dealEndTime", models.TimeField()),
                ("dealDayofWeek", models.CharField(max_length=10)),
                ("dealType", models.CharField(max_length=20)),
                ("dealDetails", models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(model_name="establishment", name="happyHourDayofWeek",),
        migrations.RemoveField(model_name="establishment", name="happyHourEndTime",),
        migrations.RemoveField(model_name="establishment", name="happyHourStartTime",),
    ]
