# Generated by Django 4.2.20 on 2025-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_deals_remove_establishment_happyhourdayofweek_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=30)),
                ("lastName", models.CharField(max_length=30)),
                ("userName", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=30)),
                ("profilePicture", models.ImageField(upload_to="")),
                ("userLocation", models.CharField(max_length=5)),
                ("listofFavorites", models.CharField(max_length=300)),
            ],
        ),
    ]
