# Generated by Django 4.2.20 on 2025-04-27 21:28

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_userdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="deals",
            name="establishment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Deals",
                to="restaurants.establishment",
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="location",
            field=mapbox_location_field.models.LocationField(default=[0.0, 0.0], map_attrs={}),
            preserve_default=False,
        ),
    ]
