# Generated by Django 4.2.20 on 2025-04-27 21:32

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_deals_establishment_establishment_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="location",
            field=mapbox_location_field.models.LocationField(
                blank=True, map_attrs={}, null=True
            ),
        ),
    ]
