# Generated by Django 4.2.20 on 2025-04-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_establishment_location"),
    ]

    operations = [
        migrations.RemoveField(model_name="establishment", name="location",),
    ]
