# Generated by Django 4.2.20 on 2025-04-27 21:42

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_remove_establishment_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="location",
            field=mapbox_location_field.models.LocationField(
                default=[0.0, 0.0], map_attrs={}
            ),
        ),
    ]
